apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysite
  name: mysite
spec:
  ports:
  - nodePort: 30501
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: mysite
  type: NodePort
